# Your project's server will run on localhost:xxxx at this port
PROXY: "http://localhost"
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "src/assets/web/dist"
  # Paths to fonts
  fonts:
    - "vendor/bower/font-awesome/fonts/**/*"
    - "vendor/bower/bootstrap/fonts/**/*"
  # Paths to images folder
  images:
    - "src/assets/web/img/**/*"
  # Paths to Less libraries, which can then be loaded with @import
  less:
  - "src/assets/web/less/app.less"

  # Paths to JavaScript libraries, which are compined into one file
  # babelscript:

  # Javascript that do not want to be run through Babel
  plainscript:
    # Yii2 scripts
    - "vendor/yiisoft/yii2/assets/yii.js"
    - "vendor/yiisoft/yii2/assets/yii.validation.js"
    - "vendor/yiisoft/yii2/assets/yii.activeForm.js"
    # Paths to your own project code are here
    - "src/assets/web/js/!(app).js"
    - "src/assets/web/js/app.js"
